Fix slow windows environment variables handling
DmitrySigalov/aws-ssm-cli pull request #20
Opened 2024-07-17 09:00 UTC by Mr1008

Previously the process of synchronizing Environment Variables was very slow. It could take even 40mins per run. It's because `Environment.SetEnvironmentVariable` when run with scope parameter other than `Process` notifies other processes running in Windows via `Interop.User32.SendMessageTimeout(new IntPtr(Interop.User32.HWND_BROADCAST), Interop.User32.WM_SETTINGCHANGE, IntPtr.Zero, (IntPtr)lParam, 0, 1000, &unused);` ([docs](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessagetimeouta)) and awaits until they handle the event. This might take a long time if a lot of messages run in the background and are badly programmed (do not support this sys event).

The change introduce direct write to the registry - exactly the same way as the `Environment.SetEnvironmentVariable` does - with the exception of sending the notification.

The notification is sent at the very end in the `CompleteActivationEnvironmentVariables` method. Thanks to this the notification is sent once at the end of the process and interested apps may refresh Environment variables (e.g. explorer.exe). Without it, you could not use updated variables without restarting the PC.

2024-07-17 09:05 UTC, hoczekjakub approved these changes

2024-07-18 05:32 UTC, marek-n-lsport approved these changes

2024-07-18 06:35 UTC, marek-n-lsport commented
Please compile new version of installer as current one doesn't have Installer.exe file

2024-07-19 09:34 UTC, Mr1008 commented
> Please include new version of installer as current one doesn't have `Installer.exe` file

Added, and updated `README.md` @marek-n-lsport

2024-07-23 06:39 UTC, DmitrySigalov requested changes
Please, delete all binaries files.
I want that installer should be compiled on the developer machine

2024-07-23 07:12 UTC, DmitrySigalov approved these changes

2024-07-23 07:15 UTC, merged